git:
  diffRenderers:
    - colorArg: always
      # pager: delta --paging=never --side-by-side --line-numbers --detect-dark-light always
      command: delta --paging=never --side-by-side --line-numbers --light
      # pager: delta --paging=never --side-by-side --line-numbers --dark
gui:
  showFileTree: false
